### PR TITLE
Add method for getting system information.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by ties** [comment]
I can't test it at the moment - but the code looks good. I would consider using a [timedelta](https://docs.python.org/3/library/datetime.html#datetime.timedelta) for the uptime. Let me know what you think about that.

**Comment by ties** [comment]
@reitermarkus let me know what you think about the usage of timedelta. If you don't think it is necessary or even inconvenient I'm ok with the current solution as well :)

**Comment by reitermarkus** [comment]
Sounds good, updated to use `timedelta`.

**Comment by reitermarkus** [comment]
Might also be good to create an enum for the `network_access` field, but I'm not sure which values are possible, or whether it's just a boolean.

**Comment by ties** [comment]
> Might also be good to create an enum for the `network_access` field, but I'm not sure which values are possible, or whether it's just a boolean.

Let's go with the current implementation. We can always revise it later!

**Comment by ties** [comment]
Merged! And I released 0.3.2 which includes this.

**Pull request merged**
